CREATE TABLE IF NOT EXISTS brands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() NOT NULL
);
